server.port=8761
spring.application.name=eureka-server

# Prevents the server from registering itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Suppress verbose Netflix internal logs
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
